//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp5 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp5.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e2dcdb3b85d1a123bfc2afb2842fc959.
        /// </summary>
        internal static string APIKEY {
            get {
                return ResourceManager.GetString("APIKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atmosphere: {0} Pa.
        /// </summary>
        internal static string AtmoshphereText {
            get {
                return ResourceManager.GetString("AtmoshphereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        internal static string BtnSettingExceptionErrorMessage {
            get {
                return ResourceManager.GetString("BtnSettingExceptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mumbai.
        /// </summary>
        internal static string City1 {
            get {
                return ResourceManager.GetString("City1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delhi.
        /// </summary>
        internal static string City2 {
            get {
                return ResourceManager.GetString("City2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolkata.
        /// </summary>
        internal static string City3 {
            get {
                return ResourceManager.GetString("City3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chennai.
        /// </summary>
        internal static string City4 {
            get {
                return ResourceManager.GetString("City4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bangalore.
        /// </summary>
        internal static string City5 {
            get {
                return ResourceManager.GetString("City5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting the weather data for {0}: {1}.
        /// </summary>
        internal static string HttpExceptionMessage {
            get {
                return ResourceManager.GetString("HttpExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity: {0}%.
        /// </summary>
        internal static string HumidityText {
            get {
                return ResourceManager.GetString("HumidityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve weather data for {0}: {1}.
        /// </summary>
        internal static string RefreshWeatherCatchMessage {
            get {
                return ResourceManager.GetString("RefreshWeatherCatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature: {0}°C.
        /// </summary>
        internal static string TemperatureText {
            get {
                return ResourceManager.GetString("TemperatureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tick.
        /// </summary>
        internal static string Tick {
            get {
                return ResourceManager.GetString("Tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one city.
        /// </summary>
        internal static string ValidationMessage {
            get {
                return ResourceManager.GetString("ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openweathermap.org/data/2.5/weather?q={0}&amp;appid={1}&amp;units=metric.
        /// </summary>
        internal static string WeatherAPIUrl {
            get {
                return ResourceManager.GetString("WeatherAPIUrl", resourceCulture);
            }
        }
    }
}
